services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - mongodb_data:/data/db
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    environment:
      - DISPLAY=:99
    depends_on:
      - frontend
      - backend
    command: >
      /bin/sh -c "Xvfb :99 -screen 0 1024x768x16 & npm run cypress:open"
volumes:
  mongodb_data: