FROM cypress/base:latest

# Install Xvfb and other dependencies
RUN apt-get update && apt-get install -y \
  xvfb \
  libgtk2.0-0 \
  libgtk-3-0 \
  libgbm-dev \
  libnotify-dev \
  libgconf-2-4 \
  libnss3 \
  libxss1 \
  libasound2 \
  libxtst6 \
  xauth

# Set environment variable to use Xvfb
ENV DISPLAY=:99

# Start Xvfb
CMD ["Xvfb", ":99", "-screen", "0", "1024x768x16", "&"]
